trigger:
- master

pool:
  vmImage: 'windows-latest'    

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src\PlantUml.Net.csproj'
    versioningScheme: 'byBuildNumber'
